version: "3"
services:
  database:
    image: postgres:16.0 # See: https://hub.docker.com/_/postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=5432 # Local database port
      - POSTGRES_DB=${DATABASE_DB:-app}
      - POSTGRES_USER=${DATABASE_USER:-app}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - TZ=Asia/Tokyo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/data:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile.local
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_DB=${DATABASE_DB:-app}
      - DATABASE_USER=${DATABASE_USER:-app}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./:/usr/src/weather-forecast/
    tty: true
    working_dir: /usr/src/weather-forecast/
