name: job
on:
  push:
    branches:
      - main
    paths:
      - weather-forecast-job/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: metalwhaledev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:weather-forecast-job"
          file: Dockerfile.deployment
          push: true
          tags: metalwhaledev/weather-forecast-job:0.1.0
